# ExternalSecret for the azure.json config file.
# Pulls the JSON blob from Key Vault (written by tofu) and
# creates the secret that ExternalDNS mounts at /etc/kubernetes/.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-config-file
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: romaine-kv
    kind: ClusterSecretStore
  target:
    name: azure-config-file
  data:
    - secretKey: azure.json
      remoteRef:
        key: external-dns-azure-config
