apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ambience-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nelsong6/ambience.git
    targetRevision: main
    path: chart/ambience
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ambience-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
